flags:
  texmath:
    network-uri: true
    executable: true
packages:
- '.'
- location:
    git: 'https://github.com/jgm/pandoc-types'
    commit: 596cb48e897dbc38ecfa51984f3f8ec78c4cdaee
extra-deps: []
resolver: lts-7.5
